/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from 'ethers';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';
import { TypedEventFilter, TypedEvent, TypedListener } from './commons';

interface ActorsUtilsInterface extends ethers.utils.Interface {
  functions: {
    'SetUpCreditLineActors()': FunctionFragment;
    'SetUpGlobalActors()': FunctionFragment;
    'SetUpPoolActors()': FunctionFragment;
    'createAdmin()': FunctionFragment;
    'createBob()': FunctionFragment;
    'createCreditLineBorrower()': FunctionFragment;
    'createCreditLineLender()': FunctionFragment;
    'createCreditLineLiquidator()': FunctionFragment;
    'createFakeAdmin()': FunctionFragment;
    'createFakeVerifier()': FunctionFragment;
    'createPoolBorrower()': FunctionFragment;
    'createPoolLenders()': FunctionFragment;
    'createPoolLiquidator()': FunctionFragment;
    'createVerifier()': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'SetUpCreditLineActors', values?: undefined): string;
  encodeFunctionData(functionFragment: 'SetUpGlobalActors', values?: undefined): string;
  encodeFunctionData(functionFragment: 'SetUpPoolActors', values?: undefined): string;
  encodeFunctionData(functionFragment: 'createAdmin', values?: undefined): string;
  encodeFunctionData(functionFragment: 'createBob', values?: undefined): string;
  encodeFunctionData(functionFragment: 'createCreditLineBorrower', values?: undefined): string;
  encodeFunctionData(functionFragment: 'createCreditLineLender', values?: undefined): string;
  encodeFunctionData(functionFragment: 'createCreditLineLiquidator', values?: undefined): string;
  encodeFunctionData(functionFragment: 'createFakeAdmin', values?: undefined): string;
  encodeFunctionData(functionFragment: 'createFakeVerifier', values?: undefined): string;
  encodeFunctionData(functionFragment: 'createPoolBorrower', values?: undefined): string;
  encodeFunctionData(functionFragment: 'createPoolLenders', values?: undefined): string;
  encodeFunctionData(functionFragment: 'createPoolLiquidator', values?: undefined): string;
  encodeFunctionData(functionFragment: 'createVerifier', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'SetUpCreditLineActors', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'SetUpGlobalActors', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'SetUpPoolActors', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createAdmin', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createBob', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createCreditLineBorrower', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createCreditLineLender', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createCreditLineLiquidator', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createFakeAdmin', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createFakeVerifier', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createPoolBorrower', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createPoolLenders', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createPoolLiquidator', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createVerifier', data: BytesLike): Result;

  events: {};
}

export class ActorsUtils extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ActorsUtilsInterface;

  functions: {
    SetUpCreditLineActors(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'SetUpCreditLineActors()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    SetUpGlobalActors(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'SetUpGlobalActors()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    SetUpPoolActors(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'SetUpPoolActors()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    createAdmin(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'createAdmin()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    createBob(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'createBob()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    createCreditLineBorrower(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'createCreditLineBorrower()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    createCreditLineLender(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'createCreditLineLender()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    createCreditLineLiquidator(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'createCreditLineLiquidator()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    createFakeAdmin(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'createFakeAdmin()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    createFakeVerifier(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'createFakeVerifier()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    createPoolBorrower(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'createPoolBorrower()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    createPoolLenders(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'createPoolLenders()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    createPoolLiquidator(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'createPoolLiquidator()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    createVerifier(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'createVerifier()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;
  };

  SetUpCreditLineActors(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'SetUpCreditLineActors()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  SetUpGlobalActors(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'SetUpGlobalActors()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  SetUpPoolActors(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'SetUpPoolActors()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  createAdmin(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'createAdmin()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  createBob(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'createBob()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  createCreditLineBorrower(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'createCreditLineBorrower()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  createCreditLineLender(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'createCreditLineLender()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  createCreditLineLiquidator(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'createCreditLineLiquidator()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  createFakeAdmin(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'createFakeAdmin()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  createFakeVerifier(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'createFakeVerifier()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  createPoolBorrower(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'createPoolBorrower()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  createPoolLenders(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'createPoolLenders()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  createPoolLiquidator(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'createPoolLiquidator()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  createVerifier(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'createVerifier()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  callStatic: {
    SetUpCreditLineActors(overrides?: CallOverrides): Promise<void>;

    'SetUpCreditLineActors()'(overrides?: CallOverrides): Promise<void>;

    SetUpGlobalActors(overrides?: CallOverrides): Promise<void>;

    'SetUpGlobalActors()'(overrides?: CallOverrides): Promise<void>;

    SetUpPoolActors(overrides?: CallOverrides): Promise<void>;

    'SetUpPoolActors()'(overrides?: CallOverrides): Promise<void>;

    createAdmin(overrides?: CallOverrides): Promise<void>;

    'createAdmin()'(overrides?: CallOverrides): Promise<void>;

    createBob(overrides?: CallOverrides): Promise<void>;

    'createBob()'(overrides?: CallOverrides): Promise<void>;

    createCreditLineBorrower(overrides?: CallOverrides): Promise<void>;

    'createCreditLineBorrower()'(overrides?: CallOverrides): Promise<void>;

    createCreditLineLender(overrides?: CallOverrides): Promise<void>;

    'createCreditLineLender()'(overrides?: CallOverrides): Promise<void>;

    createCreditLineLiquidator(overrides?: CallOverrides): Promise<void>;

    'createCreditLineLiquidator()'(overrides?: CallOverrides): Promise<void>;

    createFakeAdmin(overrides?: CallOverrides): Promise<void>;

    'createFakeAdmin()'(overrides?: CallOverrides): Promise<void>;

    createFakeVerifier(overrides?: CallOverrides): Promise<void>;

    'createFakeVerifier()'(overrides?: CallOverrides): Promise<void>;

    createPoolBorrower(overrides?: CallOverrides): Promise<void>;

    'createPoolBorrower()'(overrides?: CallOverrides): Promise<void>;

    createPoolLenders(overrides?: CallOverrides): Promise<void>;

    'createPoolLenders()'(overrides?: CallOverrides): Promise<void>;

    createPoolLiquidator(overrides?: CallOverrides): Promise<void>;

    'createPoolLiquidator()'(overrides?: CallOverrides): Promise<void>;

    createVerifier(overrides?: CallOverrides): Promise<void>;

    'createVerifier()'(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    SetUpCreditLineActors(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'SetUpCreditLineActors()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    SetUpGlobalActors(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'SetUpGlobalActors()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    SetUpPoolActors(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'SetUpPoolActors()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    createAdmin(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'createAdmin()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    createBob(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'createBob()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    createCreditLineBorrower(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'createCreditLineBorrower()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    createCreditLineLender(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'createCreditLineLender()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    createCreditLineLiquidator(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'createCreditLineLiquidator()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    createFakeAdmin(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'createFakeAdmin()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    createFakeVerifier(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'createFakeVerifier()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    createPoolBorrower(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'createPoolBorrower()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    createPoolLenders(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'createPoolLenders()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    createPoolLiquidator(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'createPoolLiquidator()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    createVerifier(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'createVerifier()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;
  };

  populateTransaction: {
    SetUpCreditLineActors(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'SetUpCreditLineActors()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    SetUpGlobalActors(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'SetUpGlobalActors()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    SetUpPoolActors(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'SetUpPoolActors()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    createAdmin(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'createAdmin()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    createBob(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'createBob()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    createCreditLineBorrower(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'createCreditLineBorrower()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    createCreditLineLender(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'createCreditLineLender()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    createCreditLineLiquidator(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'createCreditLineLiquidator()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    createFakeAdmin(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'createFakeAdmin()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    createFakeVerifier(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'createFakeVerifier()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    createPoolBorrower(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'createPoolBorrower()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    createPoolLenders(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'createPoolLenders()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    createPoolLiquidator(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'createPoolLiquidator()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    createVerifier(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'createVerifier()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;
  };
}
