/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from 'ethers';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';
import { TypedEventFilter, TypedEvent, TypedListener } from './commons';

interface ISavingsAccountInterface extends ethers.utils.Interface {
  functions: {
    'approve(address,address,uint256)': FunctionFragment;
    'approveFromToCreditLine(address,address,uint256)': FunctionFragment;
    'decreaseAllowance(address,address,uint256)': FunctionFragment;
    'depositTo(uint256,address,address,address)': FunctionFragment;
    'getTotalAsset(address,address)': FunctionFragment;
    'increaseAllowance(address,address,uint256)': FunctionFragment;
    'switchStrategy(address,address,address,uint256)': FunctionFragment;
    'transfer(address,address,address,uint256)': FunctionFragment;
    'transferFrom(address,address,address,address,uint256)': FunctionFragment;
    'userLockedBalance(address,address,address)': FunctionFragment;
    'withdraw(address,uint256,address,address,bool)': FunctionFragment;
    'withdrawAll(address)': FunctionFragment;
    'withdrawFrom(address,address,uint256,address,address,bool)': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'approve', values: [string, string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'approveFromToCreditLine', values: [string, string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'decreaseAllowance', values: [string, string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'depositTo', values: [BigNumberish, string, string, string]): string;
  encodeFunctionData(functionFragment: 'getTotalAsset', values: [string, string]): string;
  encodeFunctionData(functionFragment: 'increaseAllowance', values: [string, string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'switchStrategy', values: [string, string, string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'transfer', values: [string, string, string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'transferFrom', values: [string, string, string, string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'userLockedBalance', values: [string, string, string]): string;
  encodeFunctionData(functionFragment: 'withdraw', values: [string, BigNumberish, string, string, boolean]): string;
  encodeFunctionData(functionFragment: 'withdrawAll', values: [string]): string;
  encodeFunctionData(functionFragment: 'withdrawFrom', values: [string, string, BigNumberish, string, string, boolean]): string;

  decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'approveFromToCreditLine', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'decreaseAllowance', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'depositTo', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getTotalAsset', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'increaseAllowance', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'switchStrategy', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'userLockedBalance', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'withdrawAll', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'withdrawFrom', data: BytesLike): Result;

  events: {
    'Approved(address,address,address,uint256)': EventFragment;
    'CreditLineAllowanceRefreshed(address,address,uint256)': EventFragment;
    'CreditLineUpdated(address)': EventFragment;
    'Deposited(address,uint256,address,address)': EventFragment;
    'StrategyRegistryUpdated(address)': EventFragment;
    'StrategySwitched(address,address,address,address)': EventFragment;
    'Transfer(address,address,address,address,uint256)': EventFragment;
    'Withdrawn(address,address,uint256,address,address)': EventFragment;
    'WithdrawnAll(address,uint256,address)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'Approved'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'CreditLineAllowanceRefreshed'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'CreditLineUpdated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Deposited'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'StrategyRegistryUpdated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'StrategySwitched'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Transfer'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'Withdrawn'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'WithdrawnAll'): EventFragment;
}

export class ISavingsAccount extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ISavingsAccountInterface;

  functions: {
    approve(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'approve(address,address,uint256)'(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    approveFromToCreditLine(
      token: string,
      from: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'approveFromToCreditLine(address,address,uint256)'(
      token: string,
      from: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    decreaseAllowance(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'decreaseAllowance(address,address,uint256)'(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositTo(
      amount: BigNumberish,
      asset: string,
      strategy: string,
      to: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'depositTo(uint256,address,address,address)'(
      amount: BigNumberish,
      asset: string,
      strategy: string,
      to: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getTotalAsset(_user: string, _asset: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'getTotalAsset(address,address)'(
      _user: string,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    increaseAllowance(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'increaseAllowance(address,address,uint256)'(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    switchStrategy(
      currentStrategy: string,
      newStrategy: string,
      asset: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'switchStrategy(address,address,address,uint256)'(
      currentStrategy: string,
      newStrategy: string,
      asset: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transfer(
      token: string,
      to: string,
      poolSavingsStrategy: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'transfer(address,address,address,uint256)'(
      token: string,
      to: string,
      poolSavingsStrategy: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferFrom(
      token: string,
      from: string,
      to: string,
      poolSavingsStrategy: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'transferFrom(address,address,address,address,uint256)'(
      token: string,
      from: string,
      to: string,
      poolSavingsStrategy: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    userLockedBalance(user: string, asset: string, strategy: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    'userLockedBalance(address,address,address)'(
      user: string,
      asset: string,
      strategy: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdraw(
      withdrawTo: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'withdraw(address,uint256,address,address,bool)'(
      withdrawTo: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawAll(_asset: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'withdrawAll(address)'(_asset: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    withdrawFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'withdrawFrom(address,address,uint256,address,address,bool)'(
      from: string,
      to: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  approve(
    token: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'approve(address,address,uint256)'(
    token: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  approveFromToCreditLine(
    token: string,
    from: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'approveFromToCreditLine(address,address,uint256)'(
    token: string,
    from: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  decreaseAllowance(
    token: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'decreaseAllowance(address,address,uint256)'(
    token: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositTo(
    amount: BigNumberish,
    asset: string,
    strategy: string,
    to: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'depositTo(uint256,address,address,address)'(
    amount: BigNumberish,
    asset: string,
    strategy: string,
    to: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getTotalAsset(_user: string, _asset: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'getTotalAsset(address,address)'(
    _user: string,
    _asset: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  increaseAllowance(
    token: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'increaseAllowance(address,address,uint256)'(
    token: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  switchStrategy(
    currentStrategy: string,
    newStrategy: string,
    asset: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'switchStrategy(address,address,address,uint256)'(
    currentStrategy: string,
    newStrategy: string,
    asset: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transfer(
    token: string,
    to: string,
    poolSavingsStrategy: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'transfer(address,address,address,uint256)'(
    token: string,
    to: string,
    poolSavingsStrategy: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferFrom(
    token: string,
    from: string,
    to: string,
    poolSavingsStrategy: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'transferFrom(address,address,address,address,uint256)'(
    token: string,
    from: string,
    to: string,
    poolSavingsStrategy: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  userLockedBalance(user: string, asset: string, strategy: string, overrides?: CallOverrides): Promise<BigNumber>;

  'userLockedBalance(address,address,address)'(
    user: string,
    asset: string,
    strategy: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdraw(
    withdrawTo: string,
    amount: BigNumberish,
    asset: string,
    strategy: string,
    withdrawShares: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'withdraw(address,uint256,address,address,bool)'(
    withdrawTo: string,
    amount: BigNumberish,
    asset: string,
    strategy: string,
    withdrawShares: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawAll(_asset: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'withdrawAll(address)'(_asset: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  withdrawFrom(
    from: string,
    to: string,
    amount: BigNumberish,
    asset: string,
    strategy: string,
    withdrawShares: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'withdrawFrom(address,address,uint256,address,address,bool)'(
    from: string,
    to: string,
    amount: BigNumberish,
    asset: string,
    strategy: string,
    withdrawShares: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    approve(token: string, to: string, amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    'approve(address,address,uint256)'(token: string, to: string, amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    approveFromToCreditLine(token: string, from: string, amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    'approveFromToCreditLine(address,address,uint256)'(
      token: string,
      from: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    decreaseAllowance(token: string, to: string, amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    'decreaseAllowance(address,address,uint256)'(token: string, to: string, amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    depositTo(amount: BigNumberish, asset: string, strategy: string, to: string, overrides?: CallOverrides): Promise<BigNumber>;

    'depositTo(uint256,address,address,address)'(
      amount: BigNumberish,
      asset: string,
      strategy: string,
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalAsset(_user: string, _asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    'getTotalAsset(address,address)'(_user: string, _asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    increaseAllowance(token: string, to: string, amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    'increaseAllowance(address,address,uint256)'(token: string, to: string, amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    switchStrategy(
      currentStrategy: string,
      newStrategy: string,
      asset: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    'switchStrategy(address,address,address,uint256)'(
      currentStrategy: string,
      newStrategy: string,
      asset: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transfer(token: string, to: string, poolSavingsStrategy: string, amount: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    'transfer(address,address,address,uint256)'(
      token: string,
      to: string,
      poolSavingsStrategy: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferFrom(
      token: string,
      from: string,
      to: string,
      poolSavingsStrategy: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    'transferFrom(address,address,address,address,uint256)'(
      token: string,
      from: string,
      to: string,
      poolSavingsStrategy: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userLockedBalance(user: string, asset: string, strategy: string, overrides?: CallOverrides): Promise<BigNumber>;

    'userLockedBalance(address,address,address)'(
      user: string,
      asset: string,
      strategy: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      withdrawTo: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    'withdraw(address,uint256,address,address,bool)'(
      withdrawTo: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawAll(_asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    'withdrawAll(address)'(_asset: string, overrides?: CallOverrides): Promise<BigNumber>;

    withdrawFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    'withdrawFrom(address,address,uint256,address,address,bool)'(
      from: string,
      to: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    Approved(
      token: null,
      from: null,
      to: null,
      amount: null
    ): TypedEventFilter<[string, string, string, BigNumber], { token: string; from: string; to: string; amount: BigNumber }>;

    CreditLineAllowanceRefreshed(
      token: null,
      from: null,
      amount: null
    ): TypedEventFilter<[string, string, BigNumber], { token: string; from: string; amount: BigNumber }>;

    CreditLineUpdated(_updatedCreditLine: null): TypedEventFilter<[string], { _updatedCreditLine: string }>;

    Deposited(
      user: null,
      amount: null,
      asset: null,
      strategy: null
    ): TypedEventFilter<[string, BigNumber, string, string], { user: string; amount: BigNumber; asset: string; strategy: string }>;

    StrategyRegistryUpdated(_updatedStrategyRegistry: null): TypedEventFilter<[string], { _updatedStrategyRegistry: string }>;

    StrategySwitched(
      user: null,
      asset: null,
      currentStrategy: null,
      newStrategy: null
    ): TypedEventFilter<
      [string, string, string, string],
      {
        user: string;
        asset: string;
        currentStrategy: string;
        newStrategy: string;
      }
    >;

    Transfer(
      token: null,
      strategy: null,
      from: null,
      to: null,
      amount: null
    ): TypedEventFilter<
      [string, string, string, string, BigNumber],
      {
        token: string;
        strategy: string;
        from: string;
        to: string;
        amount: BigNumber;
      }
    >;

    Withdrawn(
      from: null,
      to: null,
      amountReceived: null,
      token: null,
      strategy: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, string],
      {
        from: string;
        to: string;
        amountReceived: BigNumber;
        token: string;
        strategy: string;
      }
    >;

    WithdrawnAll(
      user: null,
      tokenReceived: null,
      asset: null
    ): TypedEventFilter<[string, BigNumber, string], { user: string; tokenReceived: BigNumber; asset: string }>;
  };

  estimateGas: {
    approve(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'approve(address,address,uint256)'(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    approveFromToCreditLine(
      token: string,
      from: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'approveFromToCreditLine(address,address,uint256)'(
      token: string,
      from: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    decreaseAllowance(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'decreaseAllowance(address,address,uint256)'(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositTo(
      amount: BigNumberish,
      asset: string,
      strategy: string,
      to: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'depositTo(uint256,address,address,address)'(
      amount: BigNumberish,
      asset: string,
      strategy: string,
      to: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getTotalAsset(_user: string, _asset: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'getTotalAsset(address,address)'(
      _user: string,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    increaseAllowance(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'increaseAllowance(address,address,uint256)'(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    switchStrategy(
      currentStrategy: string,
      newStrategy: string,
      asset: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'switchStrategy(address,address,address,uint256)'(
      currentStrategy: string,
      newStrategy: string,
      asset: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transfer(
      token: string,
      to: string,
      poolSavingsStrategy: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'transfer(address,address,address,uint256)'(
      token: string,
      to: string,
      poolSavingsStrategy: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferFrom(
      token: string,
      from: string,
      to: string,
      poolSavingsStrategy: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'transferFrom(address,address,address,address,uint256)'(
      token: string,
      from: string,
      to: string,
      poolSavingsStrategy: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    userLockedBalance(user: string, asset: string, strategy: string, overrides?: CallOverrides): Promise<BigNumber>;

    'userLockedBalance(address,address,address)'(
      user: string,
      asset: string,
      strategy: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      withdrawTo: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'withdraw(address,uint256,address,address,bool)'(
      withdrawTo: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawAll(_asset: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'withdrawAll(address)'(_asset: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    withdrawFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'withdrawFrom(address,address,uint256,address,address,bool)'(
      from: string,
      to: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approve(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'approve(address,address,uint256)'(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    approveFromToCreditLine(
      token: string,
      from: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'approveFromToCreditLine(address,address,uint256)'(
      token: string,
      from: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    decreaseAllowance(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'decreaseAllowance(address,address,uint256)'(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositTo(
      amount: BigNumberish,
      asset: string,
      strategy: string,
      to: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'depositTo(uint256,address,address,address)'(
      amount: BigNumberish,
      asset: string,
      strategy: string,
      to: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getTotalAsset(
      _user: string,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'getTotalAsset(address,address)'(
      _user: string,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    increaseAllowance(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'increaseAllowance(address,address,uint256)'(
      token: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    switchStrategy(
      currentStrategy: string,
      newStrategy: string,
      asset: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'switchStrategy(address,address,address,uint256)'(
      currentStrategy: string,
      newStrategy: string,
      asset: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transfer(
      token: string,
      to: string,
      poolSavingsStrategy: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'transfer(address,address,address,uint256)'(
      token: string,
      to: string,
      poolSavingsStrategy: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferFrom(
      token: string,
      from: string,
      to: string,
      poolSavingsStrategy: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'transferFrom(address,address,address,address,uint256)'(
      token: string,
      from: string,
      to: string,
      poolSavingsStrategy: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    userLockedBalance(user: string, asset: string, strategy: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'userLockedBalance(address,address,address)'(
      user: string,
      asset: string,
      strategy: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      withdrawTo: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'withdraw(address,uint256,address,address,bool)'(
      withdrawTo: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawAll(_asset: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'withdrawAll(address)'(_asset: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    withdrawFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'withdrawFrom(address,address,uint256,address,address,bool)'(
      from: string,
      to: string,
      amount: BigNumberish,
      asset: string,
      strategy: string,
      withdrawShares: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
